run:
  timeout: 5m

linters:
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - durationcheck
    - errorlint
    - gochecknoinits
    - gosec
    - importas
    - misspell
    - nakedret
    - nolintlint
    - revive
    - unconvert
    - unparam
    - wastedassign

linters-settings:
  revive:
    rules:
      - name: dot-imports
        disabled: true
  staticcheck:
    checks:
      - all
      - -SA1019

issues:
  exclude-dirs:
    - third_party
    - builtin
    - examples